services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
      - shared_net

  web:
    image: nginx:alpine
    container_name: web
    ports:
      - "8081:80"  # Expose port 8081 on localhost
    volumes:
      - ./html:/usr/share/nginx/html  # Mount the hello world HTML page
      - ./html/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - grafana  # Start after Grafana to avoid any potential conflicts
    restart: unless-stopped
    networks:
      - backend
      - shared_net

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
    environment:
      - GF_INSTALL_PLUGINS=
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=${POSTGRES_HOST}
      - GF_DATABASE_NAME=${POSTGRES_DB}
      - GF_DATABASE_USER=${POSTGRES_USER}
      - GF_DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - GF_DATABASE_SSL_MODE=disable
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_LOGS=/var/log/grafana
      - GF_SERVER_HTTP_PORT=3000
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_SERVER_ALLOW_EMBEDDING=true
      - GF_SERVER_ROOT_URL=http://${GRAFANA_HOST:-localhost}/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SECURITY_HEADERS_FRAME_DENY=false
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend
      - shared_net

  create_tables:
    build:
      context: ./create_tables  # Directory containing Dockerfile for create_tables.py
    container_name: create_tables
    restart: "no"  # Do not restart after completion
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - ./flags:/flags
    networks:
      - backend
      - shared_net

  gdelt_connect:
    build:
      context: ./gdelt_connect  # Directory containing Dockerfile for fetch_gdelt_and_upload.py
    container_name: gdelt_connect
    restart: always  # Restart if it stops
    healthcheck:
      test: ["CMD-SHELL", "test -d /flags || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - ./flags:/flags
    networks:
      - backend
      - shared_net

volumes:
  grafana-data:
    driver: local
  postgres_data:
    driver: local

networks:
  backend:
    driver: bridge
  shared_net:
    driver: bridge
